try {
    var output = getMessage('Hello', 'Uma')
}
catch (ex){
    console.log('code throws an exception')
    console.log(ex)
}

